<a href="https://colab.research.google.com/github/bylejakiN7/Data_Science/blob/main/intro_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
np.__version__

'1.21.6'

In [5]:
x = np.array([1,3])
x

array([1, 3])

In [6]:
print(x)

[1 3]


In [7]:
np.arange(start=2, stop=224, step=14)

array([  2,  16,  30,  44,  58,  72,  86, 100, 114, 128, 142, 156, 170,
       184, 198, 212])

In [8]:
np.linspace(start=2, stop=10, num=6)

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

In [9]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
A.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [12]:
A^-1

array([-4, -2, -5, -3])

In [13]:
X = np.array([[1, 3], [-2,0]])
Y = np.array([[6,0],[-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [14]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [15]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [16]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [17]:
np.random.seed(0)

In [18]:
np.random.randn()

1.764052345967664

In [19]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [20]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [21]:
np.random.rand(10,4)

array([[0.19658236, 0.36872517, 0.82099323, 0.09710128],
       [0.83794491, 0.09609841, 0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552, 0.73926358, 0.03918779],
       [0.28280696, 0.12019656, 0.2961402 , 0.11872772],
       [0.31798318, 0.41426299, 0.0641475 , 0.69247212],
       [0.56660145, 0.26538949, 0.52324805, 0.09394051],
       [0.5759465 , 0.9292962 , 0.31856895, 0.66741038],
       [0.13179786, 0.7163272 , 0.28940609, 0.18319136],
       [0.58651293, 0.02010755, 0.82894003, 0.00469548],
       [0.67781654, 0.27000797, 0.73519402, 0.96218855]])

In [22]:
np.random.randint(10)

8

In [23]:
np.random.randint(low=10, high=150, size= 12)

array([ 82,  29, 105,  82,  77,  71,  24, 106,  14, 149,  96, 131])

In [24]:
np.random.choice([3,2,1,4])

2

In [25]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np. random.shuffle(data)
data

array([2, 4, 3, 7, 1, 6, 5, 9, 0, 8])

In [27]:
np.exp(1)

2.718281828459045

In [28]:
np.sqrt(9)

3.0

In [29]:
np.all([2, 3, 4])

True

In [30]:
A = np.random.rand(5)
A

array([0.50132438, 0.95608363, 0.6439902 , 0.42385505, 0.60639321])

In [31]:
np.argmax(A)

1

In [32]:
A[np.argmax(A)]

0.9560836347232239

In [33]:
np.argmin(A)

3

In [34]:
A[np.argmin(A)]

0.4238550485581797

In [35]:
np.argsort(A)

array([3, 0, 4, 2, 1])

In [36]:
np.max(A)

0.9560836347232239

In [37]:
np.mean(A)

0.6263292957131336

In [38]:
np.std(A)

0.18224671639823387

In [39]:
np.median(A)

0.6063932141279244

In [40]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
A[0]

array([0, 1, 2, 3, 4])

In [43]:
A[:, 0]

array([ 0,  5, 10, 15])

In [44]:
A[:, -1]

array([ 4,  9, 14, 19])

In [45]:
A[1,1]

6

In [46]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [47]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [49]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [51]:
for row in A:
  print(row[0])

0
5
10
15


In [52]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [54]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [55]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [56]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [57]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [58]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [59]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [60]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])